from typing import List, Dict, Any
from openai import OpenAI
from app.config import settings

class LLMSynthesizerService:
    def __init__(self):
        self.client = OpenAI(
            base_url="https://api.groq.com/openai/v1",
            api_key=settings.GROQ_API_KEY
        )

    def generate_report(self, profile: Dict[str, Any], portfolio: List[Dict[str, Any]], unallocated_cash: float) -> str:
        """
        Takes the calculated portfolio math and contextually summarizes it into a professional narrative.
        """
        # Format the numbers clearly for the LLM context prompt
        portfolio_summary_text = ""
        for asset in portfolio:
            portfolio_summary_text += (
                f"- {asset['name']} ({asset['symbol']}): Allocate {asset['allocation_percentage']}% "
                f"(₹{asset['suggested_capital_allocation']}). Buy {asset['suggested_shares_to_buy']} shares "
                f"at ₹{asset['current_price']} per share.\n"
            )

        system_prompt = (
            "You are an expert quantitative research analyst and portfolio manager.\n"
            "Your task is to write a highly professional, clear, and actionable investment rationale "
            "based on a mathematically optimized portfolio allocation generated by our systems.\n\n"
            "Guidelines:\n"
            "1. Explain why this distribution makes sense for their explicit sector choices and risk profile.\n"
            "2. Be candid about risk parameters (mention Betas or market dynamics if relevant).\n"
            "3. Provide concrete step-by-step execution guidance.\n"
            "4. End with a standard professional disclaimer stating that this is an AI simulation and not direct financial advice."
        )

        user_content = (
            f"User Profile:\n"
            f"- Total Investment Amount: ₹{profile.get('investment_amount')}\n"
            f"- Holding Period: {profile.get('time_horizon_years')} years\n"
            f"- Target Sectors: {', '.join(profile.get('sectors', []))}\n"
            f"- Risk Tolerance: {profile.get('risk_profile')}\n\n"
            f"Calculated Optimal Portfolio Allocation:\n"
            f"{portfolio_summary_text}"
            f"- Leftover Idle Cash: ₹{unallocated_cash}\n\n"
            f"Please write the personalized advice narrative now:"
        )

        response = self.client.chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content}
            ],
            temperature=0.7 # Slight variance for fluid language synthesis
        )

        return response.choices[0].message.content

llm_synthesizer_service = LLMSynthesizerService()